import { StyleSheet } from "react-native";
import { THEME } from "../../theme";

export const styles = StyleSheet.create({
  container: {
    height: "100%",
    width: "100%",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  goBackButton: {
    width: 32,
    height: 32,
    marginLeft: 26,
    alignItems: "center",
  },
  goHomeButton: {
    alignItems: "center",
    width: 24,
    height: 24,
    marginRight: 26,
  },
  header: {
    marginTop: 42,
    height: 60,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FFFFFF",
  },
  headerTittle: {
    fontSize: THEME.FONT_SIZE.TITLE,
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
    color: THEME.COLORS.TEXT_BLACK,
  },
  cartItems: {
    justifyContent: "center",
    alignItems: "center",
    width: "96%",
    height: 690,
  },
  cartItemsList: {
    alignItems: "center",
    justifyContent: "center",
    paddingBottom: 12,
  },
  emptyComponent: {
    marginVertical: 120,
    alignItems: "center",
    justifyContent: "center",
    width: 280,
    height: 400,
  },
  emptyText: {
    fontSize: THEME.FONT_SIZE.LARGER,
    color: THEME.COLORS.TEXT_GRAY,
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 120,
  },
  emptyPlusButton: {
    width: 76,
    height: 76,
    borderRadius: 40,
    marginTop: 152,
    alignItems: "center",
    justifyContent: "center",
  },
  cartFooterShadow: {
    width: "98%",
    height: 66,
    backgroundColor: "#rgba(199, 199, 199, 0.31)",
    borderRadius: 20,
  },
  cartFooter: {
    width: "98%",
    height: 60,
    backgroundColor: "#FFFFFF",
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 2,
    marginLeft: 12,
    borderRadius: 20,
  },
  cartFooterTotal: {
    paddingLeft: 12,
    fontFamily: THEME.FONT_FAMILY.BOLD,
    fontSize: THEME.FONT_SIZE.TITLE,
  },
  cartSubmitButton: {
    width: 120,
    height: 40,
    borderRadius: 20,
    backgroundColor: THEME.COLORS.MAIN_400,
    color: "white",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    marginRight: 12,
  },
  cartSubmitButtonText: {
    color: "white",
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
    fontSize: THEME.FONT_SIZE.LARGE,
    textAlign: "center",
    marginRight: 2,
    lineHeight: 18,
  },
  sentOrderModalComponent: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "red",
  },
  sentOrderLogo: {
    width: 200,
    height: 140,
    position: "absolute",
    bottom: 110,
  },
  sentOrderId: {
    marginTop: 140,
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
    fontSize: THEME.FONT_SIZE.SUBTITLE,
  },
  sentOrderModalComponentDiv: {
    position: "absolute",
    top: 180,
    left: 25,
    width: 360,
    height: 420,
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: 20,
    borderWidth: 2,
    borderColor: "#000000",
    alignItems: "center",
  },
  sentOrderModalComponentIcon: {
    position: "absolute",
    top: 24,
  },
  sentOrderModalComponentText: {
    width: 320,
    marginTop: 42,
    textAlign: "center",
    fontSize: 38,
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
  },
  sentOrderModalComponentOkButton: {
    width: 80,
    height: 40,
    position: "absolute",
    bottom: 28,
    alignItems: "center",
    justifyContent: "center",
  },
  sentOrderModalComponentOkButtonText: {
    fontSize: THEME.FONT_SIZE.LARGER,
    fontFamily: THEME.FONT_FAMILY.SEMI_BOLD,
  },
});
